// Bengali (বাংলা) translations
const bn = {
    language: 'বাংলা',
    languageCode: 'bn',
    nav: { symptomChecker: 'লক্ষণ পরীক্ষক', visionScanner: 'ভিশন স্ক্যানার', aiHealthChat: 'AI স্বাস্থ্য চ্যাট', bookAppointment: 'অ্যাপয়েন্টমেন্ট বুক করুন', history: 'ইতিহাস', admin: 'অ্যাডমিন', emergency: 'জরুরি', signIn: 'সাইন ইন', signUp: 'সাইন আপ' },
    home: { badge: 'AI-চালিত লক্ষণ বিশ্লেষণ', heroTitle: 'আপনার', heroHighlight: 'লক্ষণগুলি', heroTitleEnd: 'আরও ভালো বুঝুন', heroDescription: 'আপনার লক্ষণগুলি সম্পর্কে শিক্ষামূলক নির্দেশনা পান, কখন চিকিৎসা সেবা নিতে হবে জানুন এবং AI-চালিত স্ব-যত্ন তথ্য অ্যাক্সেস করুন।', checkSymptoms: 'লক্ষণ পরীক্ষা করুন', learnMore: 'আরও জানুন', freeToUse: 'বিনামূল্যে ব্যবহার', noRegistration: 'নিবন্ধন প্রয়োজন নেই', featureAnalysis: 'লক্ষণ বিশ্লেষণ', featureAnalysisDesc: 'AI-চালিত নির্দেশনা', featureSelfCare: 'স্ব-যত্ন পরামর্শ', featureSelfCareDesc: 'প্রমাণ-ভিত্তিক সুপারিশ', featureEducation: 'স্বাস্থ্য শিক্ষা', featureEducationDesc: 'রোগ সম্পর্কে জানুন', howItWorks: 'এটি কীভাবে কাজ করে', step1Title: 'লক্ষণ বর্ণনা করুন', step1Desc: 'আপনি কী অনুভব করছেন বলুন', step2Title: 'AI বিশ্লেষণ', step2Desc: 'আমাদের AI আপনার লক্ষণ বিশ্লেষণ করে', step3Title: 'নির্দেশনা পান', step3Desc: 'শিক্ষামূলক স্বাস্থ্য তথ্য পান', statsTitle: 'ব্যবহারকারীদের বিশ্বাস', statsChecks: 'লক্ষণ পরীক্ষা', statsConditions: 'রোগ অন্তর্ভুক্ত', statsAvailability: 'প্রাপ্যতা', statsSatisfaction: 'সন্তুষ্টি', whyTitle: 'HealthLens কীভাবে আপনাকে সাহায্য করে', whyDesc: 'আমাদের AI-চালিত সুবিধাগুলির সাথে স্বাস্থ্য শিক্ষার ভবিষ্যৎ অভিজ্ঞতা করুন', whySymptomEd: 'লক্ষণ শিক্ষা', whySymptomEdDesc: 'আপনার লক্ষণের সম্ভাব্য কারণ সম্পর্কে জানুন।', whyAiChat: 'AI স্বাস্থ্য চ্যাট', whyAiChatDesc: 'ফলো-আপ প্রশ্ন করুন এবং তাৎক্ষণিক উত্তর পান।', whyRisk: 'ঝুঁকি মূল্যায়ন', whyRiskDesc: 'স্বাস্থ্য সিদ্ধান্তকে অগ্রাধিকার দিতে ঝুঁকির স্তর জানুন।', whySeekCare: 'কখন যত্ন নেবেন', whySeekCareDesc: 'জানুন কখন লক্ষণে পেশাদার মনোযোগ প্রয়োজন।', whySelfCare: 'স্ব-যত্ন পরামর্শ', whySelfCareDesc: 'ব্যক্তিগত স্ব-যত্ন সুপারিশ পান।' },
    checker: { title: 'লক্ষণ পরীক্ষক', subtitle: 'AI-চালিত স্বাস্থ্য নির্দেশনার জন্য আপনার লক্ষণ বর্ণনা করুন', ageLabel: 'বয়স', agePlaceholder: 'আপনার বয়স লিখুন', genderLabel: 'লিঙ্গ', genderOptions: { select: 'লিঙ্গ নির্বাচন করুন', male: 'পুরুষ', female: 'মহিলা', other: 'অন্যান্য', preferNotToSay: 'বলতে চাই না' }, symptomsLabel: 'আপনার লক্ষণ বর্ণনা করুন', symptomsPlaceholder: 'যেমন, গত ৩ দিন ধরে আমার মাথাব্যথা, বমি বমি ভাব ও ক্লান্তি হচ্ছে...', durationLabel: 'সময়কাল', durationOptions: { select: 'সময়কাল নির্বাচন করুন', lessThan24: '২৪ ঘণ্টার কম', oneToThree: '১-৩ দিন', threeToSeven: '৩-৭ দিন', oneToTwoWeeks: '১-২ সপ্তাহ', twoToFourWeeks: '২-৪ সপ্তাহ', moreThanMonth: 'এক মাসের বেশি' }, severityLabel: 'তীব্রতা', analyzeButton: 'লক্ষণ বিশ্লেষণ করুন', analyzing: 'বিশ্লেষণ হচ্ছে...', disclaimer: 'এই টুলটি শুধুমাত্র শিক্ষামূলক তথ্য প্রদান করে। এটি পেশাদার চিকিৎসা পরামর্শের বিকল্প নয়।', validation: { ageRequired: 'অনুগ্রহ করে আপনার বয়স লিখুন', ageRange: 'বয়স ১ থেকে ১২০ এর মধ্যে হতে হবে', symptomsRequired: 'অনুগ্রহ করে আপনার লক্ষণ বর্ণনা করুন', symptomsMin: 'অনুগ্রহ করে আরও বিস্তারিত দিন (কমপক্ষে ১০ অক্ষর)', durationRequired: 'অনুগ্রহ করে সময়কাল নির্বাচন করুন' } },
    result: { title: 'আপনার স্বাস্থ্য রিপোর্ট', subtitle: 'AI-চালিত বিশ্লেষণ সম্পন্ন', downloadPdf: 'PDF ডাউনলোড করুন', emailPlaceholder: 'আপনার ইমেইল লিখুন', sendByEmail: 'ইমেইলে রিপোর্ট পাঠান', riskAssessment: 'ঝুঁকি মূল্যায়ন', severity: 'তীব্রতা', riskLow: 'কম ঝুঁকি', riskMedium: 'মাঝারি ঝুঁকি', riskHigh: 'উচ্চ ঝুঁকি', riskLowMsg: 'আপনার লক্ষণের ভিত্তিতে, এটি কম ঝুঁকিপূর্ণ পরিস্থিতি।', riskMediumMsg: 'নিবিড়ভাবে পর্যবেক্ষণ করুন এবং শীঘ্রই চিকিৎসকের পরামর্শ নিন।', riskHighMsg: 'অনুগ্রহ করে দ্রুত চিকিৎসা সেবা নেওয়ার কথা বিবেচনা করুন।', age: 'বয়স', gender: 'লিঙ্গ', duration: 'সময়কাল', youReported: 'আপনি জানিয়েছেন', possibleConditions: 'সম্ভাব্য অবস্থা', possibleConditionsHint: 'বিস্তারিত দেখতে ট্যাপ করুন • শুধু শিক্ষামূলক', selfCareTips: 'স্ব-যত্ন পরামর্শ', selfCareTipsHint: 'ব্যক্তিগত সুপারিশ', seeDoctor: 'ডাক্তার দেখান যদি', seeDoctorHint: 'সতর্কতা চিহ্ন', emergencySigns: 'জরুরি চিহ্ন', emergencySignsHint: 'অবিলম্বে মনোযোগ দিন', howWeReached: 'আমরা এই ফলাফলে কীভাবে পৌঁছেছি', howWeReachedHint: 'AI বিশ্লেষণ স্বচ্ছতা', symptomsAnalyzed: 'লক্ষণ বিশ্লেষিত', durationConsidered: 'সময়কাল বিবেচিত', severityWeighted: 'তীব্রতা ভার', transparencyNote: 'আমাদের AI চিকিৎসা জ্ঞান ভিত্তির বিপরীতে প্যাটার্ন ম্যাচিং ব্যবহার করে আপনার লক্ষণ বিশ্লেষণ করেছে। ফলাফল শুধুমাত্র শিক্ষামূলক।', talkToAiDoctor: 'AI ডাক্তারের সাথে কথা বলুন', talkToAiDoctorDesc: 'তাৎক্ষণিক ফলো-আপ প্রশ্ন করুন', bookAppointment: 'অ্যাপয়েন্টমেন্ট বুক করুন', bookAppointmentDesc: 'পরামর্শ নির্ধারণ করুন', checkDifferent: 'ভিন্ন লক্ষণ পরীক্ষা করুন', disclaimer: 'এই বিশ্লেষণ শুধুমাত্র শিক্ষামূলক উদ্দেশ্যে। সর্বদা যোগ্য স্বাস্থ্য পেশাদারের পরামর্শ নিন।' },
    chat: { title: 'AI স্বাস্থ্য চ্যাট', subtitle: 'স্বাস্থ্য সম্পর্কিত প্রশ্ন জিজ্ঞাসা করুন', inputPlaceholder: 'আপনার স্বাস্থ্য প্রশ্ন টাইপ করুন...', disclaimer: 'AI প্রদত্ত তথ্য শুধুমাত্র শিক্ষামূলক।', suggestedQuestions: ['মাথাব্যথার সাধারণ কারণ কী?', 'আমি কীভাবে ঘুমের মান উন্নত করতে পারি?', 'কখন ডাক্তার দেখানো উচিত?'], contextLabel: 'আপনার সাম্প্রতিক লক্ষণ পরীক্ষার ভিত্তিতে' },
    about: { badge: 'AI-চালিত লক্ষণ বিশ্লেষণ', title: 'HealthLens: আপনার ব্যক্তিগত স্বাস্থ্য শিক্ষা সহকারী', description: 'আমাদের লক্ষ্য সকলের জন্য স্বাস্থ্য শিক্ষা সহজলভ্য করা। HealthLens উন্নত AI ব্যবহার করে আপনার লক্ষণ বুঝতে সাহায্য করে।', tryFree: 'বিনামূল্যে HealthLens ব্যবহার করুন', missionTitle: 'আমাদের লক্ষ্য', missionDesc: 'আমরা বিশ্বাস করি সকলের নির্ভরযোগ্য স্বাস্থ্য তথ্য পাওয়ার অধিকার আছে।', featuresTitle: 'আমাদের বৈশিষ্ট্য', userStoriesTitle: 'কারা HealthLens ব্যবহার করে', whyTitle: 'কেন HealthLens বেছে নেবেন' },
    book: { title: 'অ্যাপয়েন্টমেন্ট বুক করুন', subtitle: 'স্বাস্থ্য সেবা প্রদানকারীর সাথে পরামর্শ নির্ধারণ করুন', backToResults: 'ফলাফলে ফিরে যান', personalInfo: 'ব্যক্তিগত তথ্য', appointmentDetails: 'অ্যাপয়েন্টমেন্ট বিবরণ', additionalInfo: 'অতিরিক্ত তথ্য', fullName: 'পূর্ণ নাম', phone: 'ফোন নম্বর', email: 'ইমেইল ঠিকানা', appointmentType: 'অ্যাপয়েন্টমেন্টের ধরন', preferredDate: 'পছন্দের তারিখ', preferredTime: 'পছন্দের সময়', selectDateFirst: 'অনুগ্রহ করে প্রথমে তারিখ নির্বাচন করুন', noSlots: 'এই তারিখে কোনো স্লট নেই', additionalNotes: 'অতিরিক্ত নোট (ঐচ্ছিক)', notesPlaceholder: 'ডাক্তারকে জানাতে চান এমন কোনো তথ্য...', symptomsFromCheck: 'আপনার পরীক্ষা থেকে লক্ষণ:', confirmBooking: 'বুকিং নিশ্চিত করুন', booking: 'বুকিং হচ্ছে...', cancellationPolicy: 'বুক করে আপনি আমাদের বাতিল নীতিতে সম্মত হচ্ছেন।' },
    history: { title: 'আপনার ইতিহাস', subtitle: 'আপনার পূর্ববর্তী লক্ষণ পরীক্ষা দেখুন', noChecks: 'এখনো কোনো লক্ষণ পরীক্ষা নেই', noChecksDesc: 'শিক্ষামূলক স্বাস্থ্য নির্দেশনা পেতে লক্ষণ পরীক্ষা শুরু করুন।', checkNow: 'এখনই লক্ষণ পরীক্ষা করুন', risk: 'ঝুঁকি', age: 'বয়স', duration: 'সময়কাল', severity: 'তীব্রতা' },
    footer: { description: 'AI-চালিত স্বাস্থ্য শিক্ষা সহকারী।', quickLinks: 'দ্রুত লিংক', home: 'হোম', symptomChecker: 'লক্ষণ পরীক্ষক', myHistory: 'আমার ইতিহাস', legal: 'আইনি', privacy: 'গোপনীয়তা নীতি', terms: 'সেবার শর্তাবলী', medicalDisclaimer: 'চিকিৎসা দাবিত্যাগ', educationalOnly: 'শুধুমাত্র শিক্ষামূলক। চিকিৎসা পরামর্শ নয়।', copyright: '© {year} {appName}. সমস্ত অধিকার সংরক্ষিত।' },
    common: { loading: 'লোড হচ্ছে...', error: 'কিছু ভুল হয়েছে', tryAgain: 'আবার চেষ্টা করুন', signInRequired: 'অনুগ্রহ করে সাইন ইন করুন', keywords: 'কীওয়ার্ড', impact: 'প্রভাব' }
};
export default bn;
