// Kannada (ಕನ್ನಡ) translations
const kn = {
    language: 'ಕನ್ನಡ', languageCode: 'kn',
    nav: { symptomChecker: 'ಲಕ್ಷಣ ಪರಿಶೀಲಕ', visionScanner: 'ವಿಷನ್ ಸ್ಕ್ಯಾನರ್', aiHealthChat: 'AI ಆರೋಗ್ಯ ಚಾಟ್', bookAppointment: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್', history: 'ಇತಿಹಾಸ', admin: 'ಅಡ್ಮಿನ್', emergency: 'ತುರ್ತು', signIn: 'ಸೈನ್ ಇನ್', signUp: 'ಸೈನ್ ಅಪ್' },
    home: { badge: 'AI-ಆಧಾರಿತ ಲಕ್ಷಣ ವಿಶ್ಲೇಷಣೆ', heroTitle: 'ನಿಮ್ಮ', heroHighlight: 'ಲಕ್ಷಣಗಳನ್ನು', heroTitleEnd: 'ಉತ್ತಮವಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ', heroDescription: 'ನಿಮ್ಮ ಲಕ್ಷಣಗಳ ಬಗ್ಗೆ ಶೈಕ್ಷಣಿಕ ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಿರಿ, AI ಮೂಲಕ ನಡೆಸಲ್ಪಡುತ್ತದೆ.', checkSymptoms: 'ಲಕ್ಷಣಗಳನ್ನು ಪರಿಶೀಲಿಸಿ', learnMore: 'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ', freeToUse: 'ಉಚಿತ ಬಳಕೆ', noRegistration: 'ನೋಂದಣಿ ಅಗತ್ಯವಿಲ್ಲ', featureAnalysis: 'ಲಕ್ಷಣ ವಿಶ್ಲೇಷಣೆ', featureAnalysisDesc: 'AI ಮಾರ್ಗದರ್ಶನ', featureSelfCare: 'ಸ್ವಯಂ-ಆರೈಕೆ ಸಲಹೆಗಳು', featureSelfCareDesc: 'ಸಾಕ್ಷ್ಯಾಧಾರಿತ ಶಿಫಾರಸುಗಳು', featureEducation: 'ಆರೋಗ್ಯ ಶಿಕ್ಷಣ', featureEducationDesc: 'ರೋಗಗಳ ಬಗ್ಗೆ ತಿಳಿಯಿರಿ', howItWorks: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ', step1Title: 'ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ', step1Desc: 'ನೀವು ಏನು ಅನುಭವಿಸುತ್ತಿದ್ದೀರಿ ಹೇಳಿ', step2Title: 'AI ವಿಶ್ಲೇಷಣೆ', step2Desc: 'ನಮ್ಮ AI ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ', step3Title: 'ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಿರಿ', step3Desc: 'ಶೈಕ್ಷಣಿಕ ಆರೋಗ್ಯ ಮಾಹಿತಿ ಪಡೆಯಿರಿ', statsTitle: 'ಬಳಕೆದಾರರ ನಂಬಿಕೆ', statsChecks: 'ಲಕ್ಷಣ ಪರಿಶೀಲನೆಗಳು', statsConditions: 'ರೋಗಗಳು ಒಳಗೊಂಡಿವೆ', statsAvailability: 'ಲಭ್ಯತೆ', statsSatisfaction: 'ತೃಪ್ತಿ', whyTitle: 'HealthLens ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ', whyDesc: 'ನಮ್ಮ AI-ಚಾಲಿತ ವೈಶಿಷ್ಟ್ಯಗಳೊಂದಿಗೆ ಆರೋಗ್ಯ ಶಿಕ್ಷಣದ ಭವಿಷ್ಯವನ್ನು ಅನುಭವಿಸಿ', whySymptomEd: 'ಲಕ್ಷಣ ಶಿಕ್ಷಣ', whySymptomEdDesc: 'ನಿಮ್ಮ ಲಕ್ಷಣಗಳ ಸಂಭವನೀಯ ಕಾರಣಗಳ ಬಗ್ಗೆ ತಿಳಿಯಿರಿ.', whyAiChat: 'AI ಆರೋಗ್ಯ ಚಾಟ್', whyAiChatDesc: 'ಫಾಲೋ-ಅಪ್ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ ಮತ್ತು ತಕ್ಷಣ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ.', whyRisk: 'ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ', whyRiskDesc: 'ಆರೋಗ್ಯ ನಿರ್ಧಾರಗಳಿಗೆ ಆದ್ಯತೆ ನೀಡಲು ಅಪಾಯ ಮಟ್ಟವನ್ನು ತಿಳಿಯಿರಿ.', whySeekCare: 'ಯಾವಾಗ ಆರೈಕೆ ಪಡೆಯಬೇಕು', whySeekCareDesc: 'ಲಕ್ಷಣಗಳಿಗೆ ವೃತ್ತಿಪರ ಗಮನ ಯಾವಾಗ ಬೇಕು ಎಂದು ತಿಳಿಯಿರಿ.', whySelfCare: 'ಸ್ವಯಂ-ಆರೈಕೆ ಸಲಹೆಗಳು', whySelfCareDesc: 'ವೈಯಕ್ತಿಕ ಸ್ವಯಂ-ಆರೈಕೆ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ.' },
    checker: { title: 'ಲಕ್ಷಣ ಪರಿಶೀಲಕ', subtitle: 'AI ಆರೋಗ್ಯ ಮಾರ್ಗದರ್ಶನಕ್ಕಾಗಿ ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ', ageLabel: 'ವಯಸ್ಸು', agePlaceholder: 'ವಯಸ್ಸು ನಮೂದಿಸಿ', genderLabel: 'ಲಿಂಗ', genderOptions: { select: 'ಲಿಂಗ ಆಯ್ಕೆಮಾಡಿ', male: 'ಪುರುಷ', female: 'ಮಹಿಳೆ', other: 'ಇತರ', preferNotToSay: 'ಹೇಳಲು ಇಷ್ಟವಿಲ್ಲ' }, symptomsLabel: 'ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ', symptomsPlaceholder: 'ಉದಾ., 3 ದಿನಗಳಿಂದ ತಲೆನೋವು, ವಾಕರಿಕೆ ಮತ್ತು ಆಯಾಸ...', durationLabel: 'ಅವಧಿ', durationOptions: { select: 'ಅವಧಿ ಆಯ್ಕೆಮಾಡಿ', lessThan24: '24 ಗಂಟೆಗಳಿಗಿಂತ ಕಡಿಮೆ', oneToThree: '1-3 ದಿನಗಳು', threeToSeven: '3-7 ದಿನಗಳು', oneToTwoWeeks: '1-2 ವಾರಗಳು', twoToFourWeeks: '2-4 ವಾರಗಳು', moreThanMonth: 'ಒಂದು ತಿಂಗಳಿಗಿಂತ ಹೆಚ್ಚು' }, severityLabel: 'ತೀವ್ರತೆ', analyzeButton: 'ಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ', analyzing: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...', disclaimer: 'ಇದು ಶೈಕ್ಷಣಿಕ ಮಾಹಿತಿ ಮಾತ್ರ.', validation: { ageRequired: 'ವಯಸ್ಸು ನಮೂದಿಸಿ', ageRange: 'ವಯಸ್ಸು 1 ರಿಂದ 120 ನಡುವೆ', symptomsRequired: 'ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ', symptomsMin: 'ಹೆಚ್ಚಿನ ವಿವರ ನೀಡಿ', durationRequired: 'ಅವಧಿ ಆಯ್ಕೆಮಾಡಿ' } },
    result: { title: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ವರದಿ', subtitle: 'AI ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ', downloadPdf: 'PDF ಡೌನ್‌ಲೋಡ್', emailPlaceholder: 'ಇಮೇಲ್ ನಮೂದಿಸಿ', sendByEmail: 'ಇಮೇಲ್‌ನಲ್ಲಿ ಕಳುಹಿಸಿ', riskAssessment: 'ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ', severity: 'ತೀವ್ರತೆ', riskLow: 'ಕಡಿಮೆ ಅಪಾಯ', riskMedium: 'ಮಧ್ಯಮ ಅಪಾಯ', riskHigh: 'ಅಧಿಕ ಅಪಾಯ', riskLowMsg: 'ಇದು ಕಡಿಮೆ ಅಪಾಯದ ಪರಿಸ್ಥಿತಿ.', riskMediumMsg: 'ಎಚ್ಚರಿಕೆಯಿಂದ ಗಮನಿಸಿ, ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.', riskHighMsg: 'ತಕ್ಷಣ ವೈದ್ಯಕೀಯ ಸಹಾಯ ಪಡೆಯಿರಿ.', age: 'ವಯಸ್ಸು', gender: 'ಲಿಂಗ', duration: 'ಅವಧಿ', youReported: 'ನೀವು ವರದಿ ಮಾಡಿದ್ದು', possibleConditions: 'ಸಂಭಾವ್ಯ ಪರಿಸ್ಥಿತಿಗಳು', possibleConditionsHint: 'ವಿಸ್ತರಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ', selfCareTips: 'ಸ್ವಯಂ-ಆರೈಕೆ ಸಲಹೆಗಳು', selfCareTipsHint: 'ವೈಯಕ್ತಿಕ ಶಿಫಾರಸುಗಳು', seeDoctor: 'ವೈದ್ಯರನ್ನು ಭೇಟಿಯಾಗಿ', seeDoctorHint: 'ಎಚ್ಚರಿಕೆ ಸಂಕೇತಗಳು', emergencySigns: 'ತುರ್ತು ಸಂಕೇತಗಳು', emergencySignsHint: 'ತಕ್ಷಣ ಗಮನ', howWeReached: 'ಈ ಫಲಿತಾಂಶಕ್ಕೆ ಹೇಗೆ ತಲುಪಿದ್ದೇವೆ', howWeReachedHint: 'AI ಪಾರದರ್ಶಕತೆ', symptomsAnalyzed: 'ಲಕ್ಷಣಗಳು ವಿಶ್ಲೇಷಿಸಲಾಗಿದೆ', durationConsidered: 'ಅವಧಿ ಪರಿಗಣಿಸಲಾಗಿದೆ', severityWeighted: 'ತೀವ್ರತೆ ತೂಕ', transparencyNote: 'ನಮ್ಮ AI ವೈದ್ಯಕೀಯ ಜ್ಞಾನದ ಆಧಾರದ ಮೇಲೆ ವಿಶ್ಲೇಷಿಸಿದೆ. ಶೈಕ್ಷಣಿಕ ಉದ್ದೇಶ ಮಾತ್ರ.', talkToAiDoctor: 'AI ವೈದ್ಯರೊಂದಿಗೆ ಮಾತನಾಡಿ', talkToAiDoctorDesc: 'ಫಾಲೋ-ಅಪ್ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ', bookAppointment: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್', bookAppointmentDesc: 'ಸಮಾಲೋಚನೆ ನಿಗದಿಪಡಿಸಿ', checkDifferent: 'ಬೇರೆ ಲಕ್ಷಣಗಳನ್ನು ಪರಿಶೀಲಿಸಿ', disclaimer: 'ಶೈಕ್ಷಣಿಕ ಉದ್ದೇಶ ಮಾತ್ರ.' },
    chat: { title: 'AI ಆರೋಗ್ಯ ಚಾಟ್', subtitle: 'ಆರೋಗ್ಯ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ', inputPlaceholder: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರಶ್ನೆ ಟೈಪ್ ಮಾಡಿ...', disclaimer: 'AI ಮಾಹಿತಿ ಶೈಕ್ಷಣಿಕ ಮಾತ್ರ.', suggestedQuestions: ['ತಲೆನೋವಿನ ಸಾಮಾನ್ಯ ಕಾರಣಗಳೇನು?', 'ನಿದ್ರೆಯ ಗುಣಮಟ್ಟ ಹೇಗೆ ಸುಧಾರಿಸುವುದು?', 'ವೈದ್ಯರನ್ನು ಯಾವಾಗ ಭೇಟಿಯಾಗಬೇಕು?'], contextLabel: 'ನಿಮ್ಮ ಇತ್ತೀಚಿನ ಲಕ್ಷಣ ಪರಿಶೀಲನೆಯ ಆಧಾರದ ಮೇಲೆ' },
    about: { badge: 'AI ಲಕ್ಷಣ ವಿಶ್ಲೇಷಣೆ', title: 'HealthLens: ನಿಮ್ಮ ಆರೋಗ್ಯ ಶಿಕ್ಷಣ ಸಹಾಯಕ', description: 'ಆರೋಗ್ಯ ಶಿಕ್ಷಣವನ್ನು ಎಲ್ಲರಿಗೂ ಲಭ್ಯವಾಗಿಸುವುದು ನಮ್ಮ ಧ್ಯೇಯ.', tryFree: 'ಉಚಿತವಾಗಿ ಪ್ರಯತ್ನಿಸಿ', missionTitle: 'ನಮ್ಮ ಧ್ಯೇಯ', missionDesc: 'ಎಲ್ಲರಿಗೂ ವಿಶ್ವಸನೀಯ ಆರೋಗ್ಯ ಮಾಹಿತಿ ಸಿಗಬೇಕು.', featuresTitle: 'ನಮ್ಮನ್ನು ವಿಶೇಷವಾಗಿಸುವುದು', userStoriesTitle: 'ಯಾರು ಬಳಸುತ್ತಾರೆ', whyTitle: 'HealthLens ಏಕೆ' },
    book: { title: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್', subtitle: 'ಸಮಾಲೋಚನೆ ನಿಗದಿಪಡಿಸಿ', backToResults: 'ಫಲಿತಾಂಶಗಳಿಗೆ ಹಿಂತಿರುಗಿ', personalInfo: 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ', appointmentDetails: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ವಿವರಗಳು', additionalInfo: 'ಹೆಚ್ಚುವರಿ ಮಾಹಿತಿ', fullName: 'ಪೂರ್ಣ ಹೆಸರು', phone: 'ಫೋನ್ ಸಂಖ್ಯೆ', email: 'ಇಮೇಲ್', appointmentType: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಪ್ರಕಾರ', preferredDate: 'ಆದ್ಯತೆಯ ದಿನಾಂಕ', preferredTime: 'ಆದ್ಯತೆಯ ಸಮಯ', selectDateFirst: 'ಮೊದಲು ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ', noSlots: 'ಸ್ಲಾಟ್‌ಗಳು ಲಭ್ಯವಿಲ್ಲ', additionalNotes: 'ಹೆಚ್ಚುವರಿ ಟಿಪ್ಪಣಿಗಳು', notesPlaceholder: 'ವೈದ್ಯರಿಗೆ ಮಾಹಿತಿ...', symptomsFromCheck: 'ಲಕ್ಷಣಗಳು:', confirmBooking: 'ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಿ', booking: 'ಬುಕ್ ಆಗುತ್ತಿದೆ...', cancellationPolicy: 'ರದ್ದತಿ ನೀತಿಗೆ ಒಪ್ಪುತ್ತೀರಿ.' },
    history: { title: 'ನಿಮ್ಮ ಇತಿಹಾಸ', subtitle: 'ಹಿಂದಿನ ಪರಿಶೀಲನೆಗಳನ್ನು ನೋಡಿ', noChecks: 'ಪರಿಶೀಲನೆಗಳಿಲ್ಲ', noChecksDesc: 'ಲಕ್ಷಣ ಪರಿಶೀಲನೆ ಪ್ರಾರಂಭಿಸಿ.', checkNow: 'ಈಗ ಪರಿಶೀಲಿಸಿ', risk: 'ಅಪಾಯ', age: 'ವಯಸ್ಸು', duration: 'ಅವಧಿ', severity: 'ತೀವ್ರತೆ' },
    footer: { description: 'AI ಆರೋಗ್ಯ ಶಿಕ್ಷಣ ಸಹಾಯಕ.', quickLinks: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು', home: 'ಮುಖಪುಟ', symptomChecker: 'ಲಕ್ಷಣ ಪರಿಶೀಲಕ', myHistory: 'ನನ್ನ ಇತಿಹಾಸ', legal: 'ಕಾನೂನು', privacy: 'ಗೌಪ್ಯತೆ ನೀತಿ', terms: 'ಸೇವಾ ನಿಯಮಗಳು', medicalDisclaimer: 'ವೈದ್ಯಕೀಯ ನಿರಾಕರಣೆ', educationalOnly: 'ಶೈಕ್ಷಣಿಕ ಉದ್ದೇಶ ಮಾತ್ರ.', copyright: '© {year} {appName}. ಎಲ್ಲ ಹಕ್ಕುಗಳು.' },
    common: { loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', error: 'ಏನೋ ತಪ್ಪಾಯಿತು', tryAgain: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ', signInRequired: 'ಸೈನ್ ಇನ್ ಮಾಡಿ', keywords: 'ಪ್ರಮುಖ ಪದಗಳು', impact: 'ಪ್ರಭಾವ' },
};
export default kn;
