// Marathi (मराठी) translations
const mr = {
    language: 'मराठी', languageCode: 'mr',
    nav: { symptomChecker: 'लक्षण तपासणी', aiHealthChat: 'AI आरोग्य चॅट', bookAppointment: 'भेट बुक करा', history: 'इतिहास', admin: 'अॅडमिन', signIn: 'साइन इन', signUp: 'साइन अप' },
    home: { badge: 'AI-संचालित लक्षण विश्लेषण', heroTitle: 'तुमच्या', heroHighlight: 'लक्षणांना', heroTitleEnd: 'चांगल्या प्रकारे समजून घ्या', heroDescription: 'तुमच्या लक्षणांबद्दल शैक्षणिक मार्गदर्शन मिळवा, AI द्वारे संचालित.', checkSymptoms: 'लक्षणे तपासा', learnMore: 'अधिक जाणून घ्या', freeToUse: 'मोफत वापर', noRegistration: 'नोंदणी आवश्यक नाही', featureAnalysis: 'लक्षण विश्लेषण', featureAnalysisDesc: 'AI मार्गदर्शन', featureSelfCare: 'स्व-काळजी सूचना', featureSelfCareDesc: 'पुराव्यावर आधारित शिफारसी', featureEducation: 'आरोग्य शिक्षण', featureEducationDesc: 'आजारांबद्दल जाणून घ्या', howItWorks: 'हे कसे कार्य करते', step1Title: 'লक्षणे सांगा', step1Desc: 'तुम्हाला काय जाणवतंय ते सांगा', step2Title: 'AI विश्लेषण', step2Desc: 'आमचे AI तुमच्या लक्षणांचे विश्लेषण करते', step3Title: 'मार्गदर्शन मिळवा', step3Desc: 'शैक्षणिक आरोग्य माहिती मिळवा', statsTitle: 'वापरकर्त्यांचा विश्वास', statsChecks: 'লक्षण तपासण्या', statsConditions: 'आजार समाविष्ट', statsAvailability: 'उपलब্ধता', statsSatisfaction: 'समाधান', whyTitle: 'HealthLens तुम्हाला कसे मदत करते', whyDesc: 'आमच्या AI-संचालित वैशিষ্ট्यांसह आरोग्य शिक्षणाचे भविष्य अनुभवा', whySymptomEd: 'लक्षण शिक्षण', whySymptomEdDesc: 'तुमच्या लक्षणांच्या संभाव्य कारणांबद्दल जाणून घ्या.', whyAiChat: 'AI आरोग्य चॅट', whyAiChatDesc: 'ফॉलো-अप प्रश्न विचারা आणि ত্বরित উত্তরে মিলवा.', whyRisk: 'जोखिम मूल्यांकन', whyRiskDesc: 'आरोग्य निर्णयांना प्राधान্য देनेसाठी जोखिम पातळी জানून ঘ্যা.', whySeekCare: 'कधी काळजी घ्यावी', whySeekCareDesc: 'लक्षणांना व्यवसায়िक लक्ष কখন आवश्यक आहे ते जाणून घ्या.', whySelfCare: 'স্ব-काळজি टिप्स', whySelfCareDesc: 'वৈয়ক্তিক স্ব-काळजी শিফারসি মিলভা.' },
    checker: { title: 'लक्षण तपासणी', subtitle: 'AI आरोग्य मार्गदर्शनासाठी तुमची लक्षणे सांगा', ageLabel: 'वय', agePlaceholder: 'तुमचे वय टाका', genderLabel: 'लिंग', genderOptions: { select: 'लिंग निवडा', male: 'पुरुष', female: 'स्त्री', other: 'इतर', preferNotToSay: 'सांगायचं नाही' }, symptomsLabel: 'तुमची लक्षणे सांगा', symptomsPlaceholder: 'उदा., गेल्या ३ दिवसांपासून डोकेदुखी, मळमळ आणि थकवा...', durationLabel: 'कालावधी', durationOptions: { select: 'कालावधी निवडा', lessThan24: '२४ तासांपेक्षा कमी', oneToThree: '१-३ दिवस', threeToSeven: '३-७ दिवस', oneToTwoWeeks: '१-२ आठवडे', twoToFourWeeks: '२-४ आठवडे', moreThanMonth: 'एक महिन्यापेक्षा जास्त' }, severityLabel: 'तीव्रता', analyzeButton: 'लक्षणे विश्लेषित करा', analyzing: 'विश्लेषण होत आहे...', disclaimer: 'हे साधन केवळ शैक्षणिक माहिती देते.', validation: { ageRequired: 'कृपया वय टाका', ageRange: 'वय १ ते १२० दरम्यान असावे', symptomsRequired: 'कृपया लक्षणे सांगा', symptomsMin: 'कृपया अधिक तपशील द्या', durationRequired: 'कृपया कालावधी निवडा' } },
    result: { title: 'तुमचा आरोग्य अहवाल', subtitle: 'AI विश्लेषण पूर्ण', downloadPdf: 'PDF डाउनलोड', emailPlaceholder: 'तुमचा ईमेल टाका', sendByEmail: 'ईमेलवर अहवाल पाठवा', riskAssessment: 'धोका मूल्यांकन', severity: 'तीव्रता', riskLow: 'कमी धोका', riskMedium: 'मध्यम धोका', riskHigh: 'उच्च धोका', riskLowMsg: 'ही कमी धोक्याची परिस्थिती आहे.', riskMediumMsg: 'काळजीपूर्वक निरीक्षण करा, लवकरच डॉक्टरांचा सल्ला घ्या.', riskHighMsg: 'कृपया ताबडतोब वैद्यकीय मदत घ्या.', age: 'वय', gender: 'लिंग', duration: 'कालावधी', youReported: 'तुम्ही सांगितलं', possibleConditions: 'संभाव्य स्थिती', possibleConditionsHint: 'विस्तारासाठी टॅप करा', selfCareTips: 'स्व-काळजी सूचना', selfCareTipsHint: 'वैयक्तिक शिफारसी', seeDoctor: 'डॉक्टरांना दाखवा', seeDoctorHint: 'सावधगिरीचे संकेत', emergencySigns: 'आणीबाणी संकेत', emergencySignsHint: 'तात्काळ लक्ष द्या', howWeReached: 'हा निकाल कसा मिळवला', howWeReachedHint: 'AI पारदर्शकता', symptomsAnalyzed: 'लक्षणांचे विश्लेषण', durationConsidered: 'कालावधी विचारात', severityWeighted: 'तीव्रता वजन', transparencyNote: 'आमच्या AI ने वैद्यकीय ज्ञानाच्या आधारे विश्लेषण केले. केवळ शैक्षणिक उद्देशासाठी.', talkToAiDoctor: 'AI डॉक्टरांशी बोला', talkToAiDoctorDesc: 'फॉलो-अप प्रश्न विचारा', bookAppointment: 'भेट बुक करा', bookAppointmentDesc: 'सल्लामसलत शेड्यूल करा', checkDifferent: 'वेगळी लक्षणे तपासा', disclaimer: 'केवळ शैक्षणिक उद्देशासाठी.' },
    chat: { title: 'AI आरोग्य चॅट', subtitle: 'आरोग्य प्रश्न विचारा', inputPlaceholder: 'तुमचा आरोग्य प्रश्न टाइप करा...', disclaimer: 'AI माहिती केवळ शैक्षणिक.', suggestedQuestions: ['डोकेदुखीची सामान्य कारणे काय?', 'झोपेची गुणवत्ता कशी सुधारावी?', 'डॉक्टरांना कधी दाखवावे?'], contextLabel: 'तुमच्या अलीकडील लक्षण तपासणीच्या आधारे' },
    about: { badge: 'AI लक्षण विश्लेषण', title: 'HealthLens: तुमचा आरोग्य शिक्षण सहाय्यक', description: 'आरोग्य शिक्षण सर्वांसाठी उपलब्ध करणे हे आमचे ध्येय.', tryFree: 'मोफत वापरून पहा', missionTitle: 'आमचे ध्येय', missionDesc: 'सर्वांना विश्वसनीय आरोग्य माहिती मिळायला हवी.', featuresTitle: 'आम्हाला वेगळं काय बनवतं', userStoriesTitle: 'कोण वापरतं', whyTitle: 'HealthLens का' },
    book: { title: 'भेट बुक करा', subtitle: 'सल्लामसलत शेड्यूल करा', backToResults: 'निकालांकडे परत', personalInfo: 'वैयक्तिक माहिती', appointmentDetails: 'भेट तपशील', additionalInfo: 'अतिरिक्त माहिती', fullName: 'पूर्ण नाव', phone: 'फोन नंबर', email: 'ईमेल', appointmentType: 'भेटीचा प्रकार', preferredDate: 'पसंतीची तारीख', preferredTime: 'पसंतीची वेळ', selectDateFirst: 'आधी तारीख निवडा', noSlots: 'स्लॉट उपलब्ध नाहीत', additionalNotes: 'अतिरिक्त टिपा', notesPlaceholder: 'डॉक्टरांना सांगायची माहिती...', symptomsFromCheck: 'लक्षणे:', confirmBooking: 'बुकिंग निश्चित करा', booking: 'बुकिंग होत आहे...', cancellationPolicy: 'रद्दीकरण धोरणास सहमत आहात.' },
    history: { title: 'तुमचा इतिहास', subtitle: 'मागील तपासण्या पहा', noChecks: 'तपासण्या नाहीत', noChecksDesc: 'लक्षण तपासणी सुरू करा.', checkNow: 'आता तपासा', risk: 'धोका', age: 'वय', duration: 'कालावधी', severity: 'तीव्रता' },
    footer: { description: 'AI आरोग्य शिक्षण सहाय्यक.', quickLinks: 'जलद दुवे', home: 'मुखपृष्ठ', symptomChecker: 'लक्षण तपासणी', myHistory: 'माझा इतिहास', legal: 'कायदेशीर', privacy: 'गोपनीयता धोरण', terms: 'सेवेच्या अटी', medicalDisclaimer: 'वैद्यकीय अस्वीकरण', educationalOnly: 'केवळ शैक्षणिक. वैद्यकीय सल्ला नाही.', copyright: '© {year} {appName}. सर्व हक्क राखीव.' },
    common: { loading: 'लोड होत आहे...', error: 'काहीतरी चुकीचे', tryAgain: 'पुन्हा प्रयत्न करा', signInRequired: 'कृपया साइन इन करा', keywords: 'कीवर्ड', impact: 'प्रभाव' },
};
export default mr;
