// Tamil (தமிழ்) translations
const ta = {
    language: 'தமிழ்', languageCode: 'ta',
    nav: { symptomChecker: 'அறிகுறி சரிபார்ப்பு', aiHealthChat: 'AI சுகாதார அரட்டை', bookAppointment: 'சந்திப்பு முன்பதிவு', history: 'வரலாறு', admin: 'நிர்வாகி', signIn: 'உள்நுழைக', signUp: 'பதிவுசெய்க' },
    home: { badge: 'AI-இயக்கப்படும் அறிகுறி பகுப்பாய்வு', heroTitle: 'உங்கள்', heroHighlight: 'அறிகுறிகளை', heroTitleEnd: 'சிறப்பாக புரிந்துகொள்ளுங்கள்', heroDescription: 'உங்கள் அறிகுறிகள் பற்றி கல்வி வழிகாட்டுதல் பெறுங்கள், AI மூலம் இயக்கப்படுகிறது.', checkSymptoms: 'அறிகுறிகளை சரிபார்க்கவும்', learnMore: 'மேலும் அறிக', freeToUse: 'இலவச பயன்பாடு', noRegistration: 'பதிவு தேவையில்லை', featureAnalysis: 'அறிகுறி பகுப்பாய்வு', featureAnalysisDesc: 'AI வழிகாட்டுதல்', featureSelfCare: 'சுய-பராமரிப்பு குறிப்புகள்', featureSelfCareDesc: 'ஆதார-அடிப்படை பரிந்துரைகள்', featureEducation: 'சுகாதார கல்வி', featureEducationDesc: 'நோய்கள் பற்றி அறிக', howItWorks: 'இது எப்படி செயல்படுகிறது', step1Title: 'அறிகுறிகளை விவரிக்கவும்', step1Desc: 'நீங்கள் என்ன அனுபவிக்கிறீர்கள் என்று சொல்லுங்கள்', step2Title: 'AI பகுப்பாய்வு', step2Desc: 'எங்கள் AI உங்கள் அறிகுறிகளை பகுப்பாய்வு செய்கிறது', step3Title: 'வழிகாட்டுதல் பெறுங்கள்', step3Desc: 'கல்வி தகவல்கள் பெறுங்கள்', statsTitle: 'பயனர்களின் நம்பிக்கை', statsChecks: 'அறிகுறி சரிபார்ப்புகள்', statsConditions: 'நோய்கள் உள்ளடங்கும்', statsAvailability: 'கிடைக்கும் தன்மை', statsSatisfaction: 'திருப்தி', whyTitle: 'HealthLens உங்களுக்கு எப்படி உதவுகிறது', whyDesc: 'எங்கள் AI-இயக்கப்படும் அம்சங்களுடன் சுகாதார கல்வியின் எதிர்காலத்தை அனுபவியுங்கள்', whySymptomEd: 'அறிகுறி கல்வி', whySymptomEdDesc: 'உங்கள் அறிகுறிகளின் சாத்தியமான காரணங்களைப் பற்றி அறியுங்கள்.', whyAiChat: 'AI சுகாதார அரட்டை', whyAiChatDesc: 'தொடர்ச்சியான கேள்விகளைக் கேளுங்கள், உடனடி பதில்களைப் பெறுங்கள்.', whyRisk: 'ஆபத்து மதிப்பீடு', whyRiskDesc: 'சுகாதார முடிவுகளுக்கு முன்னுரிமை அளிக்க ஆபத்து நிலையைப் பெறுங்கள்.', whySeekCare: 'எப்போது கவனிக்க வேண்டும்', whySeekCareDesc: 'அறிகுறிகளுக்கு தொழில்முறை கவனிப்பு எப்போது தேவை என்பதை அறியுங்கள்.', whySelfCare: 'சுய-பராமரிப்பு குறிப்புகள்', whySelfCareDesc: 'தனிப்பயனாக்கப்பட்ட சுய-பராமரிப்பு பரிந்துரைகளைப் பெறுங்கள்.' },
    checker: { title: 'அறிகுறி சரிபார்ப்பு', subtitle: 'AI சுகாதார வழிகாட்டுதலுக்கு அறிகுறிகளை விவரிக்கவும்', ageLabel: 'வயது', agePlaceholder: 'வயதை உள்ளிடவும்', genderLabel: 'பாலினம்', genderOptions: { select: 'பாலினம் தேர்வு', male: 'ஆண்', female: 'பெண்', other: 'மற்றவை', preferNotToSay: 'சொல்ல விரும்பவில்லை' }, symptomsLabel: 'அறிகுறிகளை விவரிக்கவும்', symptomsPlaceholder: 'எ.கா., 3 நாட்களாக தலைவலி, குமட்டல் மற்றும் சோர்வு...', durationLabel: 'கால அளவு', durationOptions: { select: 'கால அளவு தேர்வு', lessThan24: '24 மணி நேரத்திற்கும் குறைவு', oneToThree: '1-3 நாட்கள்', threeToSeven: '3-7 நாட்கள்', oneToTwoWeeks: '1-2 வாரங்கள்', twoToFourWeeks: '2-4 வாரங்கள்', moreThanMonth: 'ஒரு மாதத்திற்கும் மேல்' }, severityLabel: 'தீவிரம்', analyzeButton: 'அறிகுறிகளை பகுப்பாய்வு செய்க', analyzing: 'பகுப்பாய்வு செய்யப்படுகிறது...', disclaimer: 'இது கல்வி தகவல் மட்டுமே.', validation: { ageRequired: 'வயதை உள்ளிடவும்', ageRange: 'வயது 1 முதல் 120 வரை', symptomsRequired: 'அறிகுறிகளை விவரிக்கவும்', symptomsMin: 'மேலும் விவரமாக குறிப்பிடவும்', durationRequired: 'கால அளவு தேர்வு செய்யவும்' } },
    result: { title: 'உங்கள் சுகாதார அறிக்கை', subtitle: 'AI பகுப்பாய்வு முடிந்தது', downloadPdf: 'PDF பதிவிறக்கம்', emailPlaceholder: 'மின்னஞ்சல் உள்ளிடவும்', sendByEmail: 'மின்னஞ்சலில் அனுப்பு', riskAssessment: 'ஆபத்து மதிப்பீடு', severity: 'தீவிரம்', riskLow: 'குறைந்த ஆபத்து', riskMedium: 'மிதமான ஆபத்து', riskHigh: 'அதிக ஆபத்து', riskLowMsg: 'இது குறைந்த ஆபத்து நிலை.', riskMediumMsg: 'கூர்ந்து கவனியுங்கள், மருத்துவரை அணுகவும்.', riskHighMsg: 'உடனடி மருத்துவ உதவி பெறுங்கள்.', age: 'வயது', gender: 'பாலினம்', duration: 'கால அளவு', youReported: 'நீங்கள் தெரிவித்தது', possibleConditions: 'சாத்தியமான நிலைமைகள்', possibleConditionsHint: 'விரிவாக்க தட்டவும்', selfCareTips: 'சுய-பராமரிப்பு குறிப்புகள்', selfCareTipsHint: 'தனிப்பயன் பரிந்துரைகள்', seeDoctor: 'மருத்துவரை பாருங்கள்', seeDoctorHint: 'எச்சரிக்கை அறிகுறிகள்', emergencySigns: 'அவசர அறிகுறிகள்', emergencySignsHint: 'உடனடி கவனம்', howWeReached: 'இந்த முடிவை எப்படி அடைந்தோம்', howWeReachedHint: 'AI வெளிப்படைத்தன்மை', symptomsAnalyzed: 'அறிகுறிகள் பகுப்பாய்வு', durationConsidered: 'கால அளவு', severityWeighted: 'தீவிரம் எடை', transparencyNote: 'எங்கள் AI மருத்துவ அறிவு அடிப்படையில் பகுப்பாய்வு செய்தது. கல்வி நோக்கம் மட்டுமே.', talkToAiDoctor: 'AI மருத்துவரிடம் பேசுங்கள்', talkToAiDoctorDesc: 'தொடர் கேள்விகள் கேளுங்கள்', bookAppointment: 'சந்திப்பு முன்பதிவு', bookAppointmentDesc: 'ஆலோசனை திட்டமிடு', checkDifferent: 'வேறு அறிகுறிகளை சரிபார்க்கவும்', disclaimer: 'கல்வி நோக்கம் மட்டுமே.' },
    chat: { title: 'AI சுகாதார அரட்டை', subtitle: 'சுகாதார கேள்விகள் கேளுங்கள்', inputPlaceholder: 'கேள்வியை தட்டச்சு செய்யவும்...', disclaimer: 'AI தகவல் கல்வி நோக்கம் மட்டுமே.', suggestedQuestions: ['தலைவலி காரணங்கள் என்ன?', 'தூக்கத்தை எப்படி மேம்படுத்துவது?', 'மருத்துவரை எப்போது பார்க்க வேண்டும்?'], contextLabel: 'சமீபத்திய அறிகுறி சரிபார்ப்பின் அடிப்படையில்' },
    about: { badge: 'AI அறிகுறி பகுப்பாய்வு', title: 'HealthLens: உங்கள் சுகாதார கல்வி உதவியாளர்', description: 'சுகாதார கல்வியை அனைவருக்கும் அணுகக்கூடியதாக மாற்றுவதே நோக்கம்.', tryFree: 'இலவசமாக முயற்சிக்கவும்', missionTitle: 'எங்கள் நோக்கம்', missionDesc: 'அனைவருக்கும் நம்பகமான சுகாதார தகவல்கள் கிடைக்க வேண்டும்.', featuresTitle: 'எங்களை தனிப்படுத்துவது', userStoriesTitle: 'யார் பயன்படுத்துகிறார்கள்', whyTitle: 'ஏன் HealthLens' },
    book: { title: 'சந்திப்பு முன்பதிவு', subtitle: 'ஆலோசனை திட்டமிடுங்கள்', backToResults: 'முடிவுகளுக்கு திரும்பு', personalInfo: 'தனிப்பட்ட தகவல்', appointmentDetails: 'சந்திப்பு விவரங்கள்', additionalInfo: 'கூடுதல் தகவல்', fullName: 'முழு பெயர்', phone: 'தொலைபேசி எண்', email: 'மின்னஞ்சல்', appointmentType: 'சந்திப்பு வகை', preferredDate: 'விருப்பமான தேதி', preferredTime: 'விருப்பமான நேரம்', selectDateFirst: 'முதலில் தேதி தேர்வு செய்யவும்', noSlots: 'நேர இடங்கள் இல்லை', additionalNotes: 'கூடுதல் குறிப்புகள்', notesPlaceholder: 'மருத்துவருக்கு தகவல்...', symptomsFromCheck: 'அறிகுறிகள்:', confirmBooking: 'முன்பதிவை உறுதிசெய்', booking: 'முன்பதிவு செய்யப்படுகிறது...', cancellationPolicy: 'ரத்து கொள்கையை ஏற்கிறீர்கள்.' },
    history: { title: 'உங்கள் வரலாறு', subtitle: 'முந்தைய சரிபார்ப்புகள்', noChecks: 'சரிபார்ப்புகள் இல்லை', noChecksDesc: 'அறிகுறி சரிபார்ப்பு தொடங்குங்கள்.', checkNow: 'இப்போது சரிபார்க்கவும்', risk: 'ஆபத்து', age: 'வயது', duration: 'கால அளவு', severity: 'தீவிரம்' },
    footer: { description: 'AI சுகாதார கல்வி உதவியாளர்.', quickLinks: 'விரைவு இணைப்புகள்', home: 'முகப்பு', symptomChecker: 'அறிகுறி சரிபார்ப்பு', myHistory: 'என் வரலாறு', legal: 'சட்ட', privacy: 'தனியுரிமை', terms: 'விதிமுறைகள்', medicalDisclaimer: 'மருத்துவ மறுப்பு', educationalOnly: 'கல்வி நோக்கம் மட்டுமே.', copyright: '© {year} {appName}. உரிமைகள் பாதுகாக்கப்பட்டவை.' },
    common: { loading: 'ஏற்றுகிறது...', error: 'ஏதோ தவறு', tryAgain: 'மீண்டும் முயற்சி', signInRequired: 'உள்நுழையவும்', keywords: 'முக்கிய வார்த்தைகள்', impact: 'தாக்கம்' },
};
export default ta;
