// Telugu (తెలుగు) translations
const te = {
    language: 'తెలుగు', languageCode: 'te',
    nav: { symptomChecker: 'లక్షణ పరీక్ష', aiHealthChat: 'AI ఆరోగ్య చాట్', bookAppointment: 'అపాయింట్‌మెంట్ బుక్', history: 'చరిత్ర', admin: 'అడ్మిన్', signIn: 'సైన్ ఇన్', signUp: 'సైన్ అప్' },
    home: { badge: 'AI-ఆధారిత లక్షణ విశ్లేషణ', heroTitle: 'మీ', heroHighlight: 'లక్షణాలను', heroTitleEnd: 'బాగా అర్థం చేసుకోండి', heroDescription: 'మీ లక్షణాల గురించి విద్యా మార్గదర్శకత్వం పొందండి, AI ద్వారా నడపబడుతుంది.', checkSymptoms: 'లక్షణాలు తనిఖీ', learnMore: 'మరింత తెలుసుకోండి', freeToUse: 'ఉచిత వాడకం', noRegistration: 'నమోదు అవసరం లేదు', featureAnalysis: 'లక్షణ విశ్లేషణ', featureAnalysisDesc: 'AI మార్గదర్శకత్వం', featureSelfCare: 'స్వీయ-సంరక్షణ చిట్కాలు', featureSelfCareDesc: 'ఆధార-ఆధారిత సిఫార్సులు', featureEducation: 'ఆరోగ్య విద్య', featureEducationDesc: 'వ్యాధుల గురించి తెలుసుకోండి', howItWorks: 'ఇది ఎలా పని చేస్తుంది', step1Title: 'లక్షణాలు వివరించండి', step1Desc: 'మీరు ఏమి అనుభవిస్తున్నారో చెప్పండి', step2Title: 'AI విశ్లేషణ', step2Desc: 'మా AI మీ లక్షణాలను విశ్లేషిస్తుంది', step3Title: 'మార్గదర్శకత్వం పొందండి', step3Desc: 'విద్యా ఆరోగ్య సమాచారం పొందండి', statsTitle: 'వినియోగదారుల నమ్మకం', statsChecks: 'లక్షణ తనిఖీలు', statsConditions: 'వ్యాధులు చేర్చబడ్డాయి', statsAvailability: 'లభ్యత', statsSatisfaction: 'సంతృప్తి', whyTitle: 'HealthLens మీకు ఎలా సహాయపడుతుంది', whyDesc: 'మా AI-ఆధారిత ఫీచర్లతో ఆరోగ్య విద్య యొక్క భవిష్యత్తును అనుభవించండి', whySymptomEd: 'లక్షణ విద్య', whySymptomEdDesc: 'మీ లక్షణాల సాధ్యమైన కారణాల గురించి తెలుసుకోండి.', whyAiChat: 'AI ఆరోగ్య చాట్', whyAiChatDesc: 'ఫాలో-అప్ ప్రశ్నలు అడగండి మరియు తక్షణ సమాధానాలు పొందండి.', whyRisk: 'రిస్క్ అసెస్‌మెంట్', whyRiskDesc: 'ఆరోగ్య నిర్ణయాలకు ప్రాధాన్యత ఇవ్వడానికి రిస్క్ స్థాయిని తెలుసుకోండి.', whySeekCare: 'ఎప్పుడు సంరక్షణ తీసుకోవాలి', whySeekCareDesc: 'లక్షణాలకు వృత్తిపరమైన శ్రద్ధ ఎప్పుడు అవసరమో తెలుసుకోండి.', whySelfCare: 'స్వీయ-సంరక్షణ చిట్కాలు', whySelfCareDesc: 'వ్యక్తిగతీకరించిన స్వీయ-సంరక్షణ సిఫార్సులు పొందండి.' },
    checker: { title: 'లక్షణ పరీక్ష', subtitle: 'AI ఆరోగ్య మార్గదర్శకత్వం కోసం మీ లక్షణాలు వివరించండి', ageLabel: 'వయస్సు', agePlaceholder: 'వయస్సు నమోదు చేయండి', genderLabel: 'లింగం', genderOptions: { select: 'లింగం ఎంచుకోండి', male: 'పురుషుడు', female: 'స్త్రీ', other: 'ఇతర', preferNotToSay: 'చెప్పడం ఇష్టం లేదు' }, symptomsLabel: 'మీ లక్షణాలు వివరించండి', symptomsPlaceholder: 'ఉదా., 3 రోజులుగా తలనొప్పి, వికారం మరియు అలసట...', durationLabel: 'వ్యవధి', durationOptions: { select: 'వ్యవధి ఎంచుకోండి', lessThan24: '24 గంటల కంటే తక్కువ', oneToThree: '1-3 రోజులు', threeToSeven: '3-7 రోజులు', oneToTwoWeeks: '1-2 వారాలు', twoToFourWeeks: '2-4 వారాలు', moreThanMonth: 'నెల కంటే ఎక్కువ' }, severityLabel: 'తీవ్రత', analyzeButton: 'లక్షణాలు విశ్లేశించండి', analyzing: 'విశ్లేషిస్తోంది...', disclaimer: 'ఇది విద్యా సమాచారం మాత్రమే.', validation: { ageRequired: 'వయస్సు నమోదు చేయండి', ageRange: 'వయస్సు 1 నుండి 120 మధ్య', symptomsRequired: 'లక్షణాలు వివరించండి', symptomsMin: 'మరింత వివరంగా చెప్పండి', durationRequired: 'వ్యవధి ఎంచుకోండి' } },
    result: { title: 'మీ ఆరోగ్య నివేదిక', subtitle: 'AI విశ్లేషణ పూర్తయింది', downloadPdf: 'PDF డౌన్‌లోడ్', emailPlaceholder: 'ఇమెయిల్ నమోదు చేయండి', sendByEmail: 'ఇమెయిల్‌లో పంపండి', riskAssessment: 'ప్రమాద అంచనా', severity: 'తీవ్రత', riskLow: 'తక్కువ ప్రమాదం', riskMedium: 'మధ్యస్థ ప్రమాదం', riskHigh: 'అధిక ప్రమాదం', riskLowMsg: 'ఇది తక్కువ ప్రమాద పరిస్థితి.', riskMediumMsg: 'జాగ్రత్తగా పరిశీలించండి, వైద్యుడిని సంప్రదించండి.', riskHighMsg: 'వెంటనే వైద్య సహాయం పొందండి.', age: 'వయస్సు', gender: 'లింగం', duration: 'వ్యవధి', youReported: 'మీరు నివేదించింది', possibleConditions: 'సాధ్యమైన పరిస్థితులు', possibleConditionsHint: 'విస్తరించడానికి టాప్ చేయండి', selfCareTips: 'స్వీయ-సంరక్షణ చిట్కాలు', selfCareTipsHint: 'వ్యక్తిగత సిఫార్సులు', seeDoctor: 'వైద్యుడిని చూడండి', seeDoctorHint: 'హెచ్చరిక సంకేతాలు', emergencySigns: 'అత్యవసర సంకేతాలు', emergencySignsHint: 'తక్షణ శ్రద్ధ', howWeReached: 'ఈ ఫలితానికి ఎలా చేరుకున్నాము', howWeReachedHint: 'AI పారదర్శకత', symptomsAnalyzed: 'లక్షణాలు విశ్లేషించబడ్డాయి', durationConsidered: 'వ్యవధి పరిగణించబడింది', severityWeighted: 'తీవ్రత బరువు', transparencyNote: 'మా AI వైద్య జ్ఞానం ఆధారంగా విశ్లేషించింది. విద్యా ప్రయోజనం మాత్రమే.', talkToAiDoctor: 'AI వైద్యుడితో మాట్లాడండి', talkToAiDoctorDesc: 'ఫాలో-అప్ ప్రశ్నలు అడగండి', bookAppointment: 'అపాయింట్‌మెంట్ బుక్', bookAppointmentDesc: 'సంప్రదింపు షెడ్యూల్', checkDifferent: 'వేరే లక్షణాలు తనిఖీ', disclaimer: 'విద్యా ప్రయోజనం మాత్రమే.' },
    chat: { title: 'AI ఆరోగ్య చాట్', subtitle: 'ఆరోగ్య ప్రశ్నలు అడగండి', inputPlaceholder: 'మీ ఆరోగ్య ప్రశ్న టైప్ చేయండి...', disclaimer: 'AI సమాచారం విద్యా ప్రయోజనం మాత్రమే.', suggestedQuestions: ['తలనొప్పికి సాధారణ కారణాలు ఏమిటి?', 'నిద్ర నాణ్యతను ఎలా మెరుగుపరచాలి?', 'వైద్యుడిని ఎప్పుడు చూడాలి?'], contextLabel: 'మీ ఇటీవలి లక్షణ తనిఖీ ఆధారంగా' },
    about: { badge: 'AI లక్షణ విశ్లేషణ', title: 'HealthLens: మీ ఆరోగ్య విద్య సహాయకుడు', description: 'ఆరోగ్య విద్యను అందరికీ అందుబాటులోకి తీసుకురావడమే మా లక్ష్యం.', tryFree: 'ఉచితంగా ప్రయత్నించండి', missionTitle: 'మా లక్ష్యం', missionDesc: 'అందరికీ నమ్మకమైన ఆరోగ్య సమాచారం అందుబాటులో ఉండాలి.', featuresTitle: 'మమ్మల్ని ప్రత్యేకంగా చేసేది', userStoriesTitle: 'ఎవరు ఉపయోగిస్తారు', whyTitle: 'HealthLens ఎందుకు' },
    book: { title: 'అపాయింట్‌మెంట్ బుక్', subtitle: 'సంప్రదింపు షెడ్యూల్ చేయండి', backToResults: 'ఫలితాలకు తిరిగి', personalInfo: 'వ్యక్తిగత సమాచారం', appointmentDetails: 'అపాయింట్‌మెంట్ వివరాలు', additionalInfo: 'అదనపు సమాచారం', fullName: 'పూర్తి పేరు', phone: 'ఫోన్ నంబర్', email: 'ఇమెయిల్', appointmentType: 'అపాయింట్‌మెంట్ రకం', preferredDate: 'ఇష్టమైన తేదీ', preferredTime: 'ఇష్టమైన సమయం', selectDateFirst: 'ముందుగా తేదీ ఎంచుకోండి', noSlots: 'స్లాట్లు లేవు', additionalNotes: 'అదనపు గమనికలు', notesPlaceholder: 'వైద్యుడికి సమాచారం...', symptomsFromCheck: 'లక్షణాలు:', confirmBooking: 'బుకింగ్ నిర్ధారించండి', booking: 'బుక్ అవుతోంది...', cancellationPolicy: 'రద్దు విధానానికి అంగీకరిస్తున్నారు.' },
    history: { title: 'మీ చరిత్ర', subtitle: 'మునుపటి తనిఖీలు చూడండి', noChecks: 'తనిఖీలు లేవు', noChecksDesc: 'లక్షణ తనిఖీ ప్రారంభించండి.', checkNow: 'ఇప్పుడు తనిఖీ చేయండి', risk: 'ప్రమాదం', age: 'వయస్సు', duration: 'వ్యవధి', severity: 'తీవ్రత' },
    footer: { description: 'AI ఆరోగ్య విద్య సహాయకుడు.', quickLinks: 'త్వరిత లింకులు', home: 'హోమ్', symptomChecker: 'లక్షణ పరీక్ష', myHistory: 'నా చరిత్ర', legal: 'చట్ట', privacy: 'గోప్యతా విధానం', terms: 'సేవా నిబంధనలు', medicalDisclaimer: 'వైద్య నిరాకరణ', educationalOnly: 'విద్యా ప్రయోజనం మాత్రమే.', copyright: '© {year} {appName}. అన్ని హక్కులు.' },
    common: { loading: 'లోడ్ అవుతోంది...', error: 'ఏదో తప్పు', tryAgain: 'మళ్ళీ ప్రయత్నించండి', signInRequired: 'సైన్ ఇన్ చేయండి', keywords: 'కీలక పదాలు', impact: 'ప్రభావం' },
};
export default te;
